version: 2
updates:
    - package-ecosystem: elm
      directory: /src/client/
      schedule:
          interval: daily
      open-pull-requests-limit: 99
    - package-ecosystem: npm
      directory: /src/client/
      schedule:
          interval: daily
      open-pull-requests-limit: 99
